### ISSUE TITLE
Gaussian mean face looks bad

### ISSUE THREAD

**Issue by ZPdesu** [adamian98/pulse#8]
Thanks for sharing the code, great job! Here is my question:

Have you tested the Gaussian mean face. It looks quite bad from my side. Is there a huge gap between this version of style GAN and the original version of tensorflow?

**Comment by adamian98** [comment]
I assume that you are using the meant latent and then feeding it through the synthesis network? You need to use both the mean and std in order to sample a Gaussian rather than feeding the mean through. For high dimensional Gaussians, most of the density lies on the surface of a hypersphere (or ellipsoid if it isn't spherical) instead of near the origin.

The weights and network should exactly match the tensorflow implementation.
